apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: ravishankarkushwaha13/flask_live_app:1.0.2
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: flask-config
            - secretRef:
                name: flask-secrets
